[package]
name = "density_clustering_wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.84"
js-sys = "0.3.69"
serde = { version = "1.0.197", features = ["derive"] }
serde-wasm-bindgen = "0.4"
density_clustering = { path = "../density_clustering" }

[dev-dependencies]
wasm-bindgen-test = "0.3.34"
